Seed file created but not launched
pcarette/trading-simulator_project2 pull request #8
Opened 2022-06-15 15:44 UTC by pcarette

2022-06-15 15:57 UTC, ArthurVEROT requested changes

2022-06-15 15:57 UTC, ArthurVEROT commented on app.js
> +require("./seed/Asset.seed");
Delete 'require("./seed/Asset.seed");'

2022-06-15 15:57 UTC, ArthurVEROT commented on models/Asset.model.js
> +              console.log(promiseAssetValue.data.price);
suppr console log pour le main branch

2022-06-15 15:57 UTC, ArthurVEROT commented on seed/Asset.seed.js
> +  {
tu peux mettre tout les données dans un fichier JSON à part? ça sera plus propre pour le seed

2022-06-15 15:57 UTC, ArthurVEROT commented on seed/Asset.seed.js
> +Array.prototype.push.apply(assets, stocks);
tu peux remplacer par "assets.push(stocks)" me dit Florian

2022-06-16 08:12 UTC, pcarette reviewed
Made all requested changes except for the arrays in the seed

2022-06-16 08:32 UTC, ArthurVEROT approved these changes

2022-06-16 08:35 UTC, merged